name       : python-et_xmlfile
version    : 1.0.1
release    : 1
homepage   : https://bitbucket.org/openpyxl/et_xmlfile/
source     :
    - https://bitbucket.org/openpyxl/et_xmlfile/get/1.0.1.tar.gz : f13d3d456a4b321c6db5308f807773ccd1f60815ba26899b3b09d63592ce5aab
license    : MIT
component  : programming.python
summary    : et_xmlfile is a low memory library for creating large XML files.
description: |
    et_xmlfile is a low memory library for creating large XML files. It is based upon the xmlfile module from lxml with the aim of allowing code to be developed that will work with both libraries. It was developed initially for the openpyxl project but is now a standalone module.
builddeps  :
    - pkgconfig(python3)
    - python-lxml
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
